### ISSUE TITLE
component problems

### ISSUE THREAD

**Issue by skinnynpale** [Yubil-Olga/Education#18]
Если много аргументов куда поступают, то лучше передавать его объектом, так как другим да и тебе становится понятно 
какой аргумент за что отвечает +footer(true, footerslogan, footerformtitle, footerformdescription, copyright, ...footernavigation).
И кстати тут ты передаешь footernavigation с оператором ... , это бесмысленно, убери его и убери с ...items в компоненте.
И почему то у тебя в pug в именах переменных не используется camelCase исправь это

**Comment by skinnynpale** [comment]
Компоненты они и на то компоненты что должны быть переиспользуемыми и гибкими

```
mixin bullet-list
  ul.bullet-list
    li.bullet-list__item Нельзя с питомцами
    li.bullet-list__item Без вечеринок и мероприятий
    li.bullet-list__item Время прибытия — после 13:00, а выезд до 12:00
```

**Comment by skinnynpale** [comment]
Нужно убрать весь хардкод из form-booking (хардкод в этом смысле значит типо статические значения к примеру от туда 38 081₽)

в review тоже нужно убрать хардкод, там где review__date

**Comment by skinnynpale** [comment]
+field({mask: false, yupe: "text", placeholder: "Фамилия"}) - yupe опечатка

**Comment by Everrest1** [comment]
Передавать параметры в миксин блока в любом случае лучше сразу объектом, даже если параметр всего один, ведь со временем их количество может поменяться и тогда придётся искать и исправлять по всему проекту.

И объект можно деструктурировать сразу в параметрах

![image](https://user-images.githubusercontent.com/43137324/89492343-7385d780-d7c2-11ea-9c42-c64bf8f6f5d0.png)

Вот как здесь

![image](https://user-images.githubusercontent.com/43137324/89492382-87c9d480-d7c2-11ea-89a6-ba1e0743ce67.png)

**Comment by Everrest1** [comment]
Можно закрыть
