### ISSUE TITLE
Именование

### ISSUE THREAD

**Issue by Everrest1** [Yubil-Olga/Education#32]
По стандартам, булевы переменные именуются с префиксами `is/are, has, with`

![image](https://user-images.githubusercontent.com/43137324/91663387-8b1e5a80-eaf9-11ea-8745-3b2bef944c48.png)

**Comment by Everrest1** [comment]
Лучше не сокращать имена без необходимости

![image](https://user-images.githubusercontent.com/43137324/91663475-11d33780-eafa-11ea-9b85-2a81bf2d835f.png)

**Comment by Everrest1** [comment]
Не нужное сокращение

![image](https://user-images.githubusercontent.com/43137324/92864634-646ff600-f40e-11ea-8749-a1f4a1cb9b72.png)

**Comment by Everrest1** [comment]
Думаю нужно назвать `isClosed`

![image](https://user-images.githubusercontent.com/43137324/92866668-d9dcc600-f410-11ea-9755-bf18e2d63c18.png)

**Comment by Everrest1** [comment]
Думаю, будет лучше, если все переменные, которые содержат текстовую строку с классом будут отражать это в их именовании

![image](https://user-images.githubusercontent.com/43137324/92868031-57ed9c80-f412-11ea-8e32-9d94fcaa0880.png)

**Comment by Everrest1** [comment]
`inactive`

![image](https://user-images.githubusercontent.com/43137324/92868113-6d62c680-f412-11ea-8f57-658127024f52.png)

**Comment by Everrest1** [comment]
Думаю имена цвета, как параметр, так и модификатор, не должны быть связаны с числовым значением css свойства, тут это непрозрачность

![image](https://user-images.githubusercontent.com/43137324/93169718-c003f180-f736-11ea-9772-847108ed6542.png)

**Comment by Hahahayabanan** [comment]
Модификатор существительное

![image](https://user-images.githubusercontent.com/43137324/93169782-eaee4580-f736-11ea-9179-dad86b0842e1.png)

**Comment by Everrest1** [comment]
Нет необходимости сокращать здесь

![image](https://user-images.githubusercontent.com/43137324/93976707-6c268780-fd8a-11ea-8ee5-2ee3f1ef84fc.png)

**Comment by Everrest1** [comment]
С маленькой буквы

![image](https://user-images.githubusercontent.com/43137324/93976974-d9d2b380-fd8a-11ea-89b9-ca417886efd4.png)
