### ISSUE TITLE
Разметка

### ISSUE THREAD

**Issue by AkhmadBabaev** [Yubil-Olga/Education#47]
https://github.com/Yubil-Olga/Education/blob/b8934c33bb686e705ef0df86b1b84a3be262e79a/src/components/calendar/calendar.pug#L2

Так будет элегантней

```pug
.calendar.js-calendar(class=isOpen && 'calendar_open js-calendar_open')
```

**Comment by AkhmadBabaev** [comment]
https://github.com/Yubil-Olga/Education/blob/b8934c33bb686e705ef0df86b1b84a3be262e79a/src/components/color-block/color-block.pug#L2-L18

Вариант установки модификатора можно упростить, примерно так как на скрине ниже.
![изображение](https://user-images.githubusercontent.com/51095975/100759471-aef78200-3401-11eb-8a01-34ee03c9214f.png)

**Comment by AkhmadBabaev** [comment]
https://github.com/Yubil-Olga/Education/blob/b8934c33bb686e705ef0df86b1b84a3be262e79a/src/components/dropdown/dropdown.pug#L6-L14

Может так 
```pug
each item in items 
  .dropdown__option.js-dropdown__option 
    +dropdown-option(item) 
```

**Comment by AkhmadBabaev** [comment]
Пройдясь по тэгам button заметил что большинство не имеют атрубита type, в таком случае по дефолту у всех кнопок становится type="submit",  в компонент что виден на скриншоте у тебя две submit кнопки.

![изображение](https://user-images.githubusercontent.com/51095975/100760936-5c1eca00-3403-11eb-871a-17f2a2f3d973.png)

**Comment by AkhmadBabaev** [comment]
https://github.com/Yubil-Olga/Education/blob/b8934c33bb686e705ef0df86b1b84a3be262e79a/src/components/rate-button/rate-button.pug#L3

Дефолтный рейтинг должен быть 0

**Comment by AkhmadBabaev** [comment]
https://github.com/Yubil-Olga/Education/blob/b8934c33bb686e705ef0df86b1b84a3be262e79a/src/pages/room-details/room-details.pug#L13-L40

Эти данные не нужны для понимания того что происходит в компоненте, а скорее наоборот приходится скроллить прежде чем добраться до сути, перенеси пожалуйста такого типа объекта в отдельный файл в папке компонента, можно использовать json или js формат.

**Comment by Yubil-Olga** [comment]
> https://github.com/Yubil-Olga/Education/blob/b8934c33bb686e705ef0df86b1b84a3be262e79a/src/components/color-block/color-block.pug#L2-L18
> 
> Вариант установки модификатора можно упростить, примерно так как на скрине ниже.
> ![изображение](https://user-images.githubusercontent.com/51095975/100759471-aef78200-3401-11eb-8a01-34ee03c9214f.png)

Было сделано так изначально, но ревьюер попросил исправить. Стоит ли опять менять код?:)
[https://github.com/Yubil-Olga/Education/issues/31#issuecomment-697178195](url)
