### ISSUE TITLE
Интерфейс

### ISSUE THREAD

**Issue by AkhmadBabaev** [Yubil-Olga/Education#49]
![изображение](https://user-images.githubusercontent.com/51095975/100765570-b4a49600-3408-11eb-9fa6-095764f5836a.png)

Все компоненты на том или ином участке имеют градиентный фон.

**Comment by AkhmadBabaev** [comment]
![изображение](https://user-images.githubusercontent.com/51095975/100765817-fa615e80-3408-11eb-85d2-045b14297811.png)

Клик на пустое пространство выделенное красным цветом переключает чекбокс.

**Comment by AkhmadBabaev** [comment]
Когда курсор находится на тексте кнопки он тоже должен выглядеть как pointer.
![изображение](https://user-images.githubusercontent.com/51095975/100766146-604de600-3409-11eb-83e2-1778b0cca916.png)

Тоже самое только для стрелки
![изображение](https://user-images.githubusercontent.com/51095975/100766360-9db27380-3409-11eb-9619-12a7b9e6cda2.png)

**Comment by Yubil-Olga** [comment]
> Когда курсор находится на тексте кнопки он тоже должен выглядеть как pointer.
> ![изображение](https://user-images.githubusercontent.com/51095975/100766146-604de600-3409-11eb-83e2-1778b0cca916.png)
> 
> Тоже самое только для стрелки
> ![изображение](https://user-images.githubusercontent.com/51095975/100766360-9db27380-3409-11eb-9619-12a7b9e6cda2.png)

Проверяла в Chrome и Mozilla, курсор pointer на тексте кнопки и на стрелке не слетает, не поняла что не так

**Comment by AkhmadBabaev** [comment]
> Проверяла в Chrome и Mozilla, курсор pointer на тексте кнопки и на стрелке не слетает, не поняла что не так

![изображение](https://user-images.githubusercontent.com/51095975/101505633-9cdb8d80-3985-11eb-88cd-c71a187afa3e.png)

**Comment by AkhmadBabaev** [comment]
Сайт должен тянуться от 320 до 1920 пикселей.
